version: '3'

services:
  MyBlog_CategoryDb:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - category_data:/data/db

  MyBlog_ReactionDb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - reaction_data:/data/db

  MyBlog_CommentDb:
    image: couchbase:community
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
      - "8095-8097"
      - "11207"
      - "11280"
    volumes:
      - comment_data:/var/lib/couchbase/data

  MyBlog_ContentDb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - content_data:/data/db

  MyBlog_IdentityDb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - identity_data:/data/db
  
  MyBlog_Rabbitmq:
    image: rabbitmq:3.11.16-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq
    container_name: MyBlogRabbitmq
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  MyBlog_LogMongo:
      image: mongo:5.0.13
      networks:
        - graylog
      ports:
        - "27021:27017"
      volumes:
        - mongo_data:/data/db
  
  MyBlog_Elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
      environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      networks:
        - graylog
      volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data


  MyBlog_Graylog:
      image: graylog/graylog:5.0
      environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
      networks:
        - graylog
      restart: always
      depends_on:
        - MyBlog_LogMongo
        - MyBlog_Elasticsearch
      ports:
      - 9000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp
      volumes:
      - graylog_journal:/usr/share/graylog/data  # yeni volume tanımı


networks:
  graylog:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  category_data:
  reaction_data:
  comment_data:
  content_data:
  identity_data:
  rabbitmq_data:
  mongo_data:
  elasticsearch_data:
  graylog_journal: